baseURL: https://liman.havelsan.com.tr
languageCode: tr-tr
title: Liman MYS | HAVELSAN Açıklab
theme: liman-hugo-v3
googleAnalytics:
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
  - identifier: home
    name: "Ana Sayfa"
    url: "/"
    weight: 1
  - identifier: about
    name: "Keşfedin"
    url: ""
    weight: 2
  - identifier: policies
    name: "Politikalar"
    parent: "about"
    url: "/#policies"
    weight: 3
  - identifier: comparison
    name: "Karşılaştırma"
    parent: "about"
    url: "/#comparison"
    weight: 2
  footer:
  - identifier: diger
    name: "Diğer"
  - identifier: havelsan
    parent: diger
    name: HAVELSAN
    url: https://www.havelsan.com.tr/
  - identifier: aciklab
    parent: diger
    name: Açıklab
    url: https://www.aciklab.org/
  - identifier: links
    name: "Yararlı Linkler"
  - identifier: documentation
    parent: links
    name: Dökümantasyon
    url: "https://docs.liman.dev/"
  - identifier: guide
    parent: links
    name: Rehber
    url: "https://docs.liman.dev/"
params:
  openGraph: true
  description: HAVELSAN Liman Merkezi Yönetim Sistemi
  navbarlogo:
    main:
      image: logo.svg
    sub:
      image: sub.svg
  hero:
    - title: Merkezi Yönetim Sistemi
      subtitle: BT süreçlerinizde bulunan bütün bileşenleri uzaktan, kararlı, güvenli ve genişletilebilir yöntemler ile merkezi olarak yönetmenizi sağlar.<br/><br/>Açık kaynak göç projelerinde Linux çekirdeğine sahip işletim sistemlerini ve diğer platformları Liman MYS ile yönetebilirsiniz.
      logos:
        - image: "aciklab.png"
      buttons:
        - text: Neden Liman MYS?
          link: "neden-liman-mys"
        - text: Demo Talebi
          link: "/iletisim/"
      image: liman-screen
    - title: Açık Kaynak Çekirdek Yazılımı
      subtitle: Liman MYS çekirdek yazılımı açık kaynak bir yazılımdır ve herkese açıktır. Github sayfamızdan kodları görüntüleyebilir ve kullanmaya hemen başlayabilirsiniz.<br/><br/>Debian depomuzu sisteminize ekleyerek, çok kısa bir sürede desteklenen işletim sistemlerine kurulum yapabilirsiniz.
      logos:
        - image: "aciklab.png"
      buttons:
        - text: Github
          link: https://github.com/limanmys
        - text: Kurulum
          link: https://depo.aciklab.org/
      image: liman-gorsel
  section_about: 
    video_link: "https://www.youtu.be/yZyScWN2IbQ"
    thumbnail: video-holder.png
    title: Liman Yönetimi
    text: "PHP dili kullanılarak Laravel Frameworkü ile geliştirilmiştir. Liman MYS özellikleri eklenti olarak isimlendirdiğimiz paket yönetim sistemi baz alınarak tasarlandı.<br />
    Liman MYS ile kullanımda olan dizinlerin (Samba, Aktif Dizin) entegrasyonu hizmetler kesintiye uğramadan sağlanmaktadır. <br />
    Liman MYS'nin bileşenleri: Liman, Kaptan, Tayfa olarak üçe ayrılmıştır. Bu bileşenler, Liman MYS'nin kararlı ve güvenli olarak çalışmasını sağlar. <br />
    Liman Mimari olarak yönetilecek uç birimlerde “C/ C++  ” programlama dili ile ile geliştirilmiş “Tayfa ” adında minimal kaynak tüketen ajanlarımız bulunmaktadır."
  section_comparison:
    title: Karşılaştırma
    subtitle: HAVELSAN Liman MYS'nin özgünlükleri
    header:
      - head:
      - head: HAVELSAN Liman MYS
      - head: Microsoft RSAT
      - head: RedHat - FreeIPA / Ansible / Spacewalk
      - head: Microsoft Windows Admin Center
      - head: Canonical Landscape
    row:
      - title: Ajansız Linux Yönetimi
        columns:
          - tick: true
          - tick: false
          - tick: true
          - tick: false
          - tick: true
      - title: Ajansız Windows Yönetimi
        columns:
          - tick: true
          - tick: true
          - tick: true
          - tick: true
          - tick: false
      - title: Web Arayüz
        columns:
          - tick: true
          - tick: false
          - tick: true
          - tick: true
          - tick: true
      - title: Microsoft Aktif Dizin Desteği
        columns:
          - tick: true
          - tick: true
          - tick: false
          - tick: true
          - tick: false
      - title: SambaDC Desteği
        columns:
          - tick: true
          - tick: false
          - tick: false
          - tick: false
          - tick: false
      - title: Linux Sistem Politika Yönetimi
        columns:
          - tick: true
          - tick: false
          - conditional: true
          - tick: false
          - conditional: true
      - title: Windows Sistem Politika Yönetimi
        columns:
          - conditional: true
          - tick: true
          - tick: false
          - tick: true
          - tick: false
      - title: Linux Sistemlere Görev Gönderme
        columns:
          - tick: true
          - tick: false
          - tick: true
          - tick: false
          - tick: true
      - title: Bulut Sistemler ile Otomatik Entegrasyon
        columns:
          - tick: false
          - tick: false
          - tick: true
          - tick: true
          - tick: false
  section_policies:
    features:
      - list:
          - li: Paket Yönetim Politikası
          - li: Servis Yönetim Politikası
          - li: Zamanlanmış Görevler Politikası
          - li: Güvenlik Duvarı Politikası
          - li: Disk Kotası Politikası
          - li: Kütük Politikası
          - li: USB Politikası
          - li: Yazıcı Politikası
          - li: Ağ Yönetimi Politikası
          - li: Mozilla Firefox Politikası
          - li: Conky Politikası
      - list:
          - li: Kota Politikası
          - li: Yetkili Kullanıcı Politikası
          - li: GRUB Politikası
          - li: Sertifika Politikası
          - li: GNOME Politikası
          - li: Masaüstü Kısayolları Politikası
          - li: Tayfa Politikası
          - li: SSSD Politikası
          - li: Samba Paylaşım Politikası
          - li: Başlat Menüsü Politikası
          - li: HAVELSAN Giriş Ekranı Politikası
      - list:
          - li: Dosya Transfer Politikası
          - li: Güç Yönetim Politikası
          - li: XFCE Politikası
          - li: Depo Adres Yönetim Politikası
          - li: Duvar Kağıdı Politikası
          - li: Merkezi Güncelleme Politikası
          - li: LibreOffice Politikası
          - li: NTP Politikası Politikası
          - li: Klavye Kısayolları Politikası
          - li: Dosya Yetkileri Politikası
          - li: SSH Yönetim Politikası
  footer:
    logo: footer-logo.png
    socialmedia:
      - link: https://github.com/limanmys
        icon: "fa fa-github"
      - link: https://www.aciklab.org/
        icon: "fa fa-globe"
      - link: mailto:aciklab@havelsan.com.tr
        icon: "fa fa-envelope"
module:
  imports:
    path: "github.com/gohugoio/hugo-mod-bootstrap-scss-v4"
